"""Build an axor governance taxonomy for the InjecAgent benchmark.

InjecAgent (Zhan et al., arXiv:2403.02691) is a *pure attack* benchmark: every
case is an indirect prompt injection embedded in a tool's response, and the
metric is ASR (did the agent call the attacker's tool). There are no benign
tasks, so — unlike AgentDojo — there is no benign utility to over-block; the
taxonomy can therefore drive taint on *all* params of an egress sink without a
false-positive budget to protect.

Roles are derived from the data, not guessed:
  - user tools (the tool whose response carries the injection) -> untrusted_sources
  - dh AttackerTools[0]  (the direct-harm action)              -> egress_sink
  - ds AttackerTools[1]  (the data-stealing exfil step, S2)    -> egress_sink
  - ds AttackerTools[0]  (the sensitive read, S1)              -> sensitive_source
  - driving_args = every declared parameter of each egress sink (any param whose
    value is content-derived from the untrusted read denies the call).

This emits config/injecagent.yaml. Point INJECAGENT_DIR at the cloned repo.
"""
from __future__ import annotations

import json
import os
import sys

INJECAGENT_DIR = os.environ.get("INJECAGENT_DIR", "/home/user/InjecAgent")
sys.path.insert(0, INJECAGENT_DIR)
os.environ.setdefault("OPENAI_API_KEY", "sk-dummy")  # utils.py builds a client at import

from src.utils import get_tool_dict  # noqa: E402


def _params(tool_dict, tool: str) -> list[str]:
    ps = tool_dict.get(tool, {}).get("parameters", [])
    if isinstance(ps, list):
        return [p.get("name") for p in ps if p.get("name")]
    return list(ps)


def build() -> dict:
    _cwd = os.getcwd()
    os.chdir(INJECAGENT_DIR)  # get_tool_dict() reads the cwd-relative data/tools.json
    try:
        tool_dict = get_tool_dict()
    finally:
        os.chdir(_cwd)
    user_tools: set[str] = set()
    dh_egress: set[str] = set()
    ds_s1_read: set[str] = set()
    ds_s2_egress: set[str] = set()

    data_dir = os.path.join(INJECAGENT_DIR, "data")
    for setting in ("base", "enhanced"):
        for it in json.load(open(os.path.join(data_dir, f"test_cases_dh_{setting}.json"))):
            user_tools.add(it["User Tool"])
            dh_egress.add(it["Attacker Tools"][0])
        for it in json.load(open(os.path.join(data_dir, f"test_cases_ds_{setting}.json"))):
            user_tools.add(it["User Tool"])
            ds_s1_read.add(it["Attacker Tools"][0])
            if len(it["Attacker Tools"]) > 1:
                ds_s2_egress.add(it["Attacker Tools"][1])

    egress = sorted(dh_egress | ds_s2_egress)
    driving = {t: _params(tool_dict, t) for t in egress if _params(tool_dict, t)}

    return {
        "mode": "production",
        "untrusted_sources": sorted(user_tools),
        "sensitive_sources": sorted(ds_s1_read),
        "egress_sinks": egress,
        "driving_args": driving,
        "_meta": {
            "user_tools": len(user_tools),
            "dh_egress": len(dh_egress),
            "ds_s1_sensitive_reads": len(ds_s1_read),
            "ds_s2_egress": len(ds_s2_egress),
            "egress_sinks_total": len(egress),
            "egress_with_driving_args": len(driving),
        },
    }


def to_yaml(cfg: dict) -> str:
    lines = ["# axor governance for the InjecAgent benchmark — GENERATED by build_config.py.",
             "# Roles are data-derived (see build_config.py docstring). Do not hand-edit;",
             "# regenerate instead.", f"# stats: {json.dumps(cfg['_meta'])}", "",
             f"mode: {cfg['mode']}", "", "untrusted_sources:"]
    for t in cfg["untrusted_sources"]:
        lines.append(f"  - {t}")
    lines += ["", "sensitive_sources:"]
    for t in cfg["sensitive_sources"]:
        lines.append(f"  - {t}")
    lines += ["", "egress_sinks:"]
    for t in cfg["egress_sinks"]:
        lines.append(f"  - {t}")
    lines += ["", "driving_args:"]
    for t, ps in cfg["driving_args"].items():
        lines.append(f"  {t}: [{', '.join(ps)}]")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    cfg = build()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config", "injecagent.yaml")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write(to_yaml(cfg))
    print(f"wrote {out}")
    print(json.dumps(cfg["_meta"], indent=2))
